### ISSUE TITLE
ValueError (invalid cast) in get_distance_plus_turns

### ISSUE THREAD

**Issue by james-ralph8555** [zdasaro/mms-competition-proxy#1]
It happens when I passed a distance value of 7 to the moveForward() function in mms-python/API.py

The trace is

exception
Traceback (most recent call last):
  File "../mms-competition-proxy/proxy.py", line 150, in <module>
    main()
  File "../mms-competition-proxy/proxy.py", line 135, in main
    and get_distance_plus_turns() > state["limit"]):
  File "../mms-competition-proxy/proxy.py", line 63, in get_distance_plus_turns
    total_distance = int(sys.stdin.readline())
ValueError: invalid literal for int() with base 10: '25.5\n'  

I fixed it by changing 
total_distance = int(sys.stdin.readline()) 
to 
total_distance = float(sys.stdin.readline())

**Comment by zdasaro** [comment]
Thank you for the fix.
